services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    env_file: ".env"
    volumes:
      - "mariadb-data:/var/lib/mysql"
    networks:
      - inception
    restart: on-failure
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    env_file: ".env"
    depends_on:
      - mariadb
    volumes:
      - "wordpress-data:/var/www"
    networks:
      - inception
    restart: on-failure
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    env_file: ".env"
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - "wordpress-data:/var/www"
    networks:
      - inception
    restart: on-failure

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /home/omoussaoui/data/wordpress
  mariadb-data:
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /home/omoussaoui/data/mariadb

networks:
  inception:
    driver: bridge

